#!/usr/bin/env bash

set -e

npm ci
npm run lint
npm run build
npm run release

if [[ -z $(git diff --quiet) ]]; then
  GIT_EMAIL="support+actions@github.com"
  GIT_USERNAME="github-actions-bot"

  git config --global user.email "$GIT_EMAIL"
  git config --global user.name "$GIT_USERNAME"

  # semantic-release has bumped the version number
  NEXT_VERSION=$(jq -r '.version' < package.json)
  NEXT_VERSION_BRANCH="release-$NEXT_VERSION"
  MESSAGE="chore: $NEXT_VERSION"

  # create new branch
  git checkout -b "$NEXT_VERSION_BRANCH"

  # add changes
  git add package.json package-lock.json
  git commit -m "$MESSAGE"

  # push branch
  git push -u origin "$NEXT_VERSION_BRANCH"

  # raise PR
  gh pr create --title "$MESSAGE" --body "ensure repository version matches reality"
fi
