#!/usr/bin/env bash

set -e

performCI() {
  npm ci
  npm run lint
  npm run build
}

keepLinearHistory() {
  PACKAGE_NAME=$(jq -r '.name' < package.json)
  REPO_VERSION=$(jq -r '.version' < package.json)

  # If we have just published a new version, it can take a couple of seconds for npm to list it.
  # Perform the version check after the "normal" steps to anticipate this.
  # This also means we get feedback on changes first as the version check is the least important.
  LATEST_VERSION=$(npm show "$PACKAGE_NAME" version)

  if [ "$REPO_VERSION" != "$LATEST_VERSION" ]; then
    echo "Version mismatch! The version number on this branch ($REPO_VERSION) does not match the latest published version ($LATEST_VERSION)."
    echo "  Please rebase this branch with main or check unmerged PRs to keep a linear history."
    echo "  Is this wrong? It could be that npm is processing the last release. Re-run this build in a few seconds."
    exit 1
  fi
}

main() {
  performCI
  keepLinearHistory
}

main
