name: Automerge
on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Validate and merge version bump PRs
        uses: guardian/release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
