name: CD
on:
  push:
    branches:
      - main
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/checkout@v2
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - name: CD
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN_2 }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
      - name: Post-release
        uses: guardian/actions-merge-release-changes-to-protected-branch@v1.0.0
        with:
          github-token: ${{ secrets.CI_TOKEN_2 }}
          package-manager: yarn
          pr-author: jamie-lynch
