name: Check
on:
  check_suite:
    types:
      - completed
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate and merge version bump PRs
        run: 'echo "testing... testing..."''
