name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
      - run: yarn build
  approveAndMerge:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Validate, approve and merge release PRs
        uses: guardian/actions-merge-release-changes-to-protected-branch@v1.0.0
        with:
          github-token: ${{ secrets.CI_TOKEN_2 }}
          package-manager: yarn
          pr-author: jamie-lynch
