name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./script/ci
  approveAndMerge:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Validate, approve and merge release PRs
        uses: guardian/post-release-action@main
        with:
          github-token: ${{ secrets.CI_TOKEN }}
          pr-author: jamie-lynch
