name: CD
on:
  push:
    branches:
      - jl/test-push
jobs:
  CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Validate and open PR
        uses: guardian/release-action@main
        with:
          github-token: ${{ secrets.CI_TOKEN }}
